name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # depend:
  #   runs-on: macos-latest
  #   steps:
  #     - name: brew install rapidjson
  #       run: |
  #         brew install rapidjson

  compile:
    runs-on: macos-latest
    # needs: [depend]
    steps:
      - name: get info
        run: |
          uname -a

      - name: get ip
        run: |
          curl ifconfig.me



      - name: brew install rapidjson
        run: |
          brew install rapidjson

      - name: checkout code
        uses: actions/checkout@v3
      # - name: Display the path by pwsh
      #   run: echo ${env:PATH}
      #   shell: pwsh
      # - name: Display github.workspace by pwsh
      #   run: |
      #     echo "github.workspace is ${{ github.workspace }}."
      #     ls ${{ github.workspace }}
      #   shell: pwsh
      - name: CMake Builds
        run: |
          cd ${{ github.workspace }}
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LIBRARY_LIBS=ON -DUSE_SHARED_LIBS=OFF
          cmake --build build --parallel 4
          cd build && ./main 1 2 3 4

      - name: debugger
        uses: shaowenchen/debugger-action@v2
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
          frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
          frp_token: ${{ secrets.FRP_TOKEN }}
          ssh_port: ${{ secrets.SSH_PORT }}

      # - name: Wait / Sleep
      #   uses: GuillaumeFalourd/wait-sleep-action@v1
      #   # uses: whatnick/wait-action@master
      #   with:
      #     time: '1h'

  # build:
  #   runs-on: macos-latest
  #   needs: compile
  #   steps:
  #   - name: 打包
  #     run: cmake --build build --parallel 4