name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # depend:
  #   runs-on: macos-latest
  #   steps:
  #     - name: brew install rapidjson
  #       run: |
  #         brew install rapidjson

  compile:
    runs-on: macos-latest
    # needs: [depend]
    steps:
      - name: get info
        run: |
          uname -a

      - name: get ip
        run: |
          curl ifconfig.me

      # - name: wget frp
      #   run: |
      #     wget https://github.com/fatedier/frp/releases/download/v0.43.0/frp_0.43.0_darwin_amd64.tar.gz
      #     tar -zxvf frp_0.43.0_darwin_amd64.tar.gz
      #     cd frp_0.43.0_darwin_amd64
      #     echo "[common]" > frpc.ini
      #     echo "server_addr = 1.117.52.41" >> frpc.ini
      #     echo "server_port = 7000" >> frpc.ini
      #     echo "token = ${{ secrets.FRP_TOKEN }}" >> frpc.ini
      #     echo "" >> frpc.ini
      #     echo "[ssh]" >> frpc.ini
      #     echo "type = tcp" >> frpc.ini
      #     echo "local_ip = 127.0.0.1" >> frpc.ini
      #     echo "local_port = 22" >> frpc.ini
      #     echo "remote_port = 6000" >> frpc.ini
      #     nohup ./frpc -c ./frpc.ini &
      #     whoami

      # - name: rsa
      #   run: |
      #     cd ~/.ssh
      #     touch authorized_keys
      #     echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZwrfLewtRgszE5VaB7VsJXz6jEM6p52c2q7u1qEGsG2G8cBJuFlWUUWEazI9gDr9beqz0+pE2fVquYqxxkxJgaSYP3yfKLKLKRubwiPbiRMka9+FuYvXl6nMjcV2Qqqpy8WHF/pEmConVLfahZtjcMkpBkQsMlI9v5aTdYz5ucgQb5c828fuGKzpuJ36Pc2tLhSW3+8c4M/hnDlqEfNfOV54822fqOJjvgL3JH+QElHhVWWXSCv1BEMGFyBmpZUkGB9ljGIZGZb1LXnwgy0bWaj1Vuoi/wKgeUhYEgixApwHnSchRauPDsSVmpNsBvD2P260Dze/eIRJgvtAtOW+z root@VM-0-9-centos" > id_rsa.pub
      #     chmod 600 authorized_keys
      #     chmod 700 ~/.ssh
      #     echo "\nPubkeyAuthentication yes" >> /etc/ssh/sshd_config

      - name: brew install rapidjson
        run: |
          brew install rapidjson

      - name: checkout code
        uses: actions/checkout@v3
      # - name: Display the path by pwsh
      #   run: echo ${env:PATH}
      #   shell: pwsh
      # - name: Display github.workspace by pwsh
      #   run: |
      #     echo "github.workspace is ${{ github.workspace }}."
      #     ls ${{ github.workspace }}
      #   shell: pwsh
      - name: CMake Builds
        run: |
          cd ${{ github.workspace }}
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LIBRARY_LIBS=ON -DUSE_SHARED_LIBS=OFF
          cmake --build build --parallel 4
          cd build && ./main 1 2 3 4

      - name: debugger
        uses: shaowenchen/debugger-action@v2
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
          frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
          frp_token: ${{ secrets.FRP_TOKEN }}
          ssh_port: ${{ secrets.SSH_PORT }}

      # - name: Wait / Sleep
      #   uses: GuillaumeFalourd/wait-sleep-action@v1
      #   # uses: whatnick/wait-action@master
      #   with:
      #     time: '1h'

  # build:
  #   runs-on: macos-latest
  #   needs: compile
  #   steps:
  #   - name: 打包
  #     run: cmake --build build --parallel 4