name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Display the path by pwsh
      #   run: echo ${env:PATH}
      #   shell: pwsh
      # - name: Display github.workspace by pwsh
      #   run: |
      #     echo "github.workspace is ${{ github.workspace }}."
      #     ls ${{ github.workspace }}
      #   shell: pwsh
      - name: CMake Builds
        run: |
          cd ${{ github.workspace }}
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LIBRARY_LIBS=ON -DUSE_SHARED_LIBS=OFF
          cmake --build build --parallel 4
        shell: pwsh

  # build:
  #   runs-on: macos-latest
  #   needs: compile
  #   steps:
  #   - name: 打包
  #     run: cmake --build build --parallel 4