name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300
        continue-on-error: true
        with:
          frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
          frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
          frp_token: ${{ secrets.FRP_TOKEN }}
          ssh_port: 29004

  build:
    runs-on: macos-latest
    needs: compile
    steps:
    - name: 打包
      run: cmake --build build --parallel 4