name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: macos-latest
    steps:
    - name: 编译
      run: |
            echo "$(ls)"

  build:
    runs-on: macos-latest
    needs: compile
    steps:
    - name: 打包
      run: cmake --build build --parallel 4