name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: macos-latest
    steps:
    - name: 编译
      run: cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LIBRARY_LIBS=ON  -DUSE_SHARED_LIBS=OFF

  build:
    runs-on: macos-latest
    needs: compile
    steps:
    - name: 打包
      run: cmake --build build --parallel 4